on: push
name: Build Checks

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run buildworker
      - uses: actions/upload-artifact@master
        with:
          name: dist-worker
          path: dist

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: dist-frontend
          path: dist
